<?php

namespace Laika\Mailman\Pipeline;

use Laika\Mailman\Message;

/**
 * What a Pipeline found in one message.
 *
 * Confidence is part of the contract rather than an implementation detail.
 * The same ticket number can turn up in a custom header, in a plus-addressed
 * recipient, in the subject, and in the body, and those are not equally
 * trustworthy:
 *
 *   header    — you set X-Ticket-ID yourself on the way out; definitive
 *   recipient — support+ticket-1234@… ; machine-generated by your own mail
 *   subject   — a human may have edited it, but conventionally reliable
 *   body      — least reliable; prose, signatures and quoted history live here
 *
 * Results are ordered by that precedence, so first() returns the most
 * trustworthy hit, and confidenceOf() tells you which tier it came from —
 * useful when a body-only match should be queued for human review rather
 * than auto-filed.
 */
class ScanResult
{
    public const HEADER = 'header';
    public const RECIPIENT = 'recipient';
    public const SUBJECT = 'subject';
    public const BODY = 'body';

    /** Most to least trustworthy. */
    public const PRECEDENCE = [self::HEADER, self::RECIPIENT, self::SUBJECT, self::BODY];

    public function __construct(
        public readonly Message $message,
        /** @var array<string,string[]> name => identifiers, best first */
        public readonly array $identifiers = [],
        /** @var array<string,string> name => confidence tier of its first hit */
        public readonly array $sources = [],
        /** @var string[] raw plus-address tags, e.g. "ticket-1234" */
        public readonly array $tags = [],
        /** @var string[] Message-ID plus In-Reply-To and References */
        public readonly array $threadIds = []
    ) {
    }

    public function has(string $name): bool
    {
        return ($this->identifiers[$name] ?? []) !== [];
    }

    /** The most trustworthy identifier for $name, or null. */
    public function first(string $name): ?string
    {
        return $this->identifiers[$name][0] ?? null;
    }

    /** @return string[] every identifier for $name, best first */
    public function all(string $name): array
    {
        return $this->identifiers[$name] ?? [];
    }

    /** @return string[] the names that matched something */
    public function names(): array
    {
        return array_keys(array_filter($this->identifiers, static fn (array $v): bool => $v !== []));
    }

    public function isEmpty(): bool
    {
        return $this->names() === [];
    }

    /** 'header' | 'recipient' | 'subject' | 'body', or null when nothing matched. */
    public function confidenceOf(string $name): ?string
    {
        return $this->sources[$name] ?? null;
    }

    /**
     * True when the identifier came from a header or a plus-addressed
     * recipient — the two tiers your own systems generate, as opposed to
     * anything a human typed.
     */
    public function isTrusted(string $name): bool
    {
        return in_array($this->confidenceOf($name), [self::HEADER, self::RECIPIENT], true);
    }

    /**
     * A reply to something we sent. Worth checking even when no identifier
     * matched: a user who strips the subject tag entirely still sends
     * In-Reply-To, so threadIds() can recover the thread when the regexes
     * cannot.
     */
    public function isReply(): bool
    {
        return $this->message->header('in-reply-to') !== null || $this->message->header('references') !== null;
    }

    /** Everything as one array, for logging. */
    public function toArray(): array
    {
        return [
            'subject' => $this->message->subject,
            'from' => $this->message->fromAddress(),
            'identifiers' => $this->identifiers,
            'sources' => $this->sources,
            'tags' => $this->tags,
            'thread_ids' => $this->threadIds,
        ];
    }
}
